import { ApiProperty } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  IsDate,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUUID,
  MaxLength,
} from 'class-validator';

export class CreateProjectDto {
  @IsString()
  @IsNotEmpty()
  @ApiProperty({ name: 'name', example: 'taskmaster' })
  name: string;

  @IsString()
  @IsOptional()
  @ApiProperty({ name: 'description', example: 'Project description' })
  description?: string;

  @IsString()
  @IsOptional()
  @MaxLength(3)
  @ApiProperty({
    name: 'key',
    example: 'TMS',
    description:
      'it will be automatically generated by the name of the project',
  })
  key?: string;

  @IsDate()
  @Type(() => Date)
  @IsNotEmpty()
  @ApiProperty({
    name: 'startDate',
    example: new Date(),
    description: 'The start date of your project',
  })
  startDate: Date; // starting date of the project

  @IsDate()
  @Type(() => Date)
  @IsNotEmpty()
  @ApiProperty({
    name: 'targetDate',
    example: new Date(),
    description: 'The expected completion date',
  })
  targetDate: Date; // estimated completion date

  @IsString()
  @IsNotEmpty()
  @ApiProperty({
    name: 'workspace',
    example: 'waredrop',
    description: 'This will create the project under a particular workspace',
  })
  workspace: string; // slug of the workspace

  @IsUUID()
  @IsOptional()
  @ApiProperty({
    name: 'lead',
    example: 'ae09fad8-457e-49fd-a0af-22a9322dc789',
    description: 'The user who will be leading this project',
    nullable: true,
  })
  lead?: string;
}
